# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  FILE: store_route_mail_like_a_pro
  MAIN_OPTIONS: "--allow-local-files"
  METADATA: "--title 'Store and Route Your Mail Like a Pro' --author 'Bart
    Dorlandt' --keywords 'mail, organization, productivity, workflow'
    --description 'A presentation about the challenges of managing physical and
    electronic mail and how to do it efficiently.'"

tasks:
  default: task -l --sort none

  mkdir:export:
    desc: Create export directory if it doesn't exist
    internal: true
    status:
      - test -d export
    cmds:
      - mkdir -p export

  export:pdf:
    desc: Export the presentation to PDF
    deps: [ mkdir:export ]
    vars:
      EXPORT_FILE: export/{{.FILE}}.pdf
      EXPORT_NOTES_FILE: export/{{.FILE}}_notes.pdf
      OPTIONS: "{{.MAIN_OPTIONS}} --pdf {{.METADATA}}"
    cmds:
      - marp {{.OPTIONS}} -o {{.EXPORT_FILE}} {{.FILE}}.md
      - marp {{.OPTIONS}} --pdf-notes -o {{.EXPORT_NOTES_FILE}} {{.FILE}}.md

  export:pptx:
    desc: Export the presentation to PPTX
    deps: [ mkdir:export ]
    vars:
      EXPORT_FILE: export/{{.FILE}}.pptx
      OPTIONS: "{{.MAIN_OPTIONS}} --pptx {{.METADATA}}"
    cmds:
      - marp {{.OPTIONS}} -o {{.EXPORT_FILE}} {{.FILE}}.md

  present:
    desc: Present the presentation
    vars:
      OPTIONS: "{{.MAIN_OPTIONS}}"
    cmds:
      - open http://localhost:8080/{{.FILE}}.md
      - marp -s {{.OPTIONS}} .

  notes:
    desc: Export the notes
    cmds:
      - marp --notes {{.FILE}}.md
      - mv json_freedom_or_chaos.txt export/
