# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  FILES:
    sh: gfind -type f -maxdepth 1 -name "store*.md" -printf "%P\n"
  MAIN_OPTIONS: "--allow-local-files"
  METADATA: "--title 'Store and Route Your Mail Like a Pro' --author 'Bart
    Dorlandt' --keywords 'mail, organization, productivity, workflow'
    --description 'A presentation about the challenges of managing physical and
    electronic mail and how to do it efficiently.'"

tasks:
  default: task -l --sort none

  mkdir:export:
    desc: Create export directory if it doesn't exist
    internal: true
    status:
      - test -d export
    cmds:
      - mkdir -p export

  export:pdf:
    desc: Export the presentation to PDF
    deps: [mkdir:export]
    vars:
      OPTIONS: "{{.MAIN_OPTIONS}} --pdf {{.METADATA}}"
    cmds:
      - for:
          var: FILES
        cmd: marp {{.OPTIONS}} -o export/{{.ITEM | replace ".md" ".pdf"}} {{.ITEM}}

  export:pptx:
    desc: Export the presentation to PPTX
    deps: [mkdir:export]
    vars:
      OPTIONS: "{{.MAIN_OPTIONS}} --pptx {{.METADATA}}"
    cmds:
      - for:
          var: FILES
        cmd: marp {{.OPTIONS}} -o export/{{.ITEM | replace ".md" ".pptx"}} {{.ITEM}}

  present:
    desc: Present the presentation
    vars:
      OPTIONS: "{{.MAIN_OPTIONS}}"
    cmds:
      - open http://localhost:8080/
      - marp -s {{.OPTIONS}} .
